spring.application.name=antojosupb

# Desactivar temporalmente la configuración de Base de Datos para que el servidor no falle al no encontrarla
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
